### ISSUE TITLE
Vertical slider issues

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#12] opened 2015-02-13 21:21 UTC
This sim has the issue: phetsims/molarity/issues/17

Troubleshooting information:
Name: Molarity
URL: http://www.colorado.edu/physics/phet/dev/html/molarity/1.1.0/molarity_en.html
Version: 1.1.0
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
Language: en-us
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by veillette** [comment] 2015-02-17 00:20
The slider had been replaced by the HSlider. Assigning the issue to @phet-steele. I'll push a new dev version to see if the problem is resolved.

**Comment by veillette** [comment] 2015-02-19 01:41
This is still present so it must be present in all sims using HSlider.

**Comment by jessegreenberg** [comment] 2016-12-14 19:30
Closing, this is being tracked now in https://github.com/phetsims/sun/issues/155.

**Closed as completed by jessegreenberg** 2016-12-14 19:30 UTC
