### ISSUE TITLE
Automated Testing Sim Error (3/29/2016 10:00 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#58] opened 2016-03-29 17:44 UTC
```
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
    at ObservableArray.inherit.push (http://phettest.colorado.edu/axon/js/ObservableArray.js?bust=1459268829434:228:15)
    at http://phettest.colorado.edu/least-squares-regression/js/least-squares-regression/model/LeastSquaresRegressionModel.js?bust=1459268829434:110:32
    at Array.forEach (native)
    at Array. (http://phettest.colorado.edu/least-squares-regression/js/least-squares-regression/model/LeastSquaresRegressionModel.js?bust=1459268829434:109:31)
    at Emitter.inherit.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1459268829434:139:49)
    at Property.inherit._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1459268829434:129:29)
    at Property.inherit._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1459268829434:117:14)
    at Property.inherit.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1459268829434:85:16)
    at Property.inherit.reset (http://phettest.colorado.edu/axon/js/Property.js?bust=1459268829434:151:14)
    at http://phettest.colorado.edu/axon/js/PropertySet.js?bust=1459268829434:171:37
```

**Comment by jessegreenberg** [comment] 2016-03-30 00:46
Ran fuzz test on sim for ~45 minutes, could not hit this error.

**Comment by jessegreenberg** [comment] 2016-03-30 00:47
From error report above, it looks like line 110 of LeastSquaresRegressionModel:

``` js
      if ( selectedDataSet === DataSet.CUSTOM ) {
        // use the savedCustomDataPoints to populate the dataPoints array
        savedCustomDataPoints.forEach( function( dataPoint ) {
          thisModel.dataPoints.push( dataPoint );
        } );
        // Add the Data Points on Graph and all the Residuals
        // For performance reason, we do it in bulk so that we don't constantly update the residuals after adding a dataPoint
        thisModel.graph.addDataPointsOnGraphAndResidualsInBulk( thisModel.dataPoints );
        thisModel.dataPoints.forEach( function( dataPoint ) {
          thisModel.addDataPointControlledListener( dataPoint );
        } );

      }
```

`thisMode.dataPoints` is getting a duplicate.

**Comment by jessegreenberg** [comment] 2016-03-30 22:47
I can reproduce this now.  Every other time I switch from a real data set to a custom data set we get a duplicate entry in the dataPoints observable array.

**Comment by jessegreenberg** [comment] 2016-03-31 00:42
In LeastSquaresRegressionModel, 

``` js
      if ( oldSelectedDataSet && oldSelectedDataSet === DataSet.CUSTOM ) {
        // add the current dataPoints on graph to savedCustomDataPoints
        debugger;
        savedCustomDataPoints = thisModel.graph.dataPointsOnGraph;
      }
```

thisModel.graph.dataPointsOnGraph is getting each data point twice.

**Comment by jessegreenberg** [comment] 2016-03-31 01:16
Since 

``` js
           if ( !model.graph.isDataPointOnList( addedDataPoint ) )
            // Add dataPoint to the array of dataPoint on graph as well as the associated residuals.
            {
              model.graph.addPointAndResiduals( addedDataPoint );
            }
```

was added to the position listener, we were adding all data points individually and then adding them in bulk via https://github.com/phetsims/least-squares-regression/issues/58#issuecomment-203173040.

To fix this, we can lazyLink the position listener so that data points are not immediately added to the graph when the position changes, and we can still add them all in bulk for performance.

**Comment by jessegreenberg** [comment] 2016-03-31 01:24
It is noticeably faster on my machine now that we are only adding in bulk.

**Comment by jessegreenberg** [comment] 2016-03-31 01:25
This has been resolved, closing.

**Closed as completed by jessegreenberg** 2016-03-31 01:25 UTC
Labels: type:bug
