### ISSUE TITLE
info button should use common component

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/least-squares-regression#76] opened 2018-03-27 18:54 UTC
Next to the selected data set is an "info" button. 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/7852916/37988331-e33929fe-31bd-11e8-9b74-169ea21d2dd3.png">

This should use the new common info button. https://github.com/phetsims/scenery-phet/issues/363

**Comment by veillette** [comment] 2022-10-14 12:37
While working on common code components in https://github.com/phetsims/least-squares-regression/issues/83, I noticed this issue.

There are color options for the info button. Below are three standard colors as shown in https://github.com/phetsims/scenery-phet/issues/363
> To clarify....
> 
> Here's what `InfoButton` looks like with default settings. Black icon on a gray button.
> 
> ![screenshot_525](https://user-images.githubusercontent.com/3046552/37991111-83e4ee0e-31c5-11e8-9bec-adc11804ccf3.png)
> 
> Here's what `InfoButton` looks like with a blue icon (`iconFill: 'rgb( 41, 106, 163 )'`). This custom color is used in masses-and-springs and pendulum lab, and is _not_ currently the default.
> 
> ![screenshot_526](https://user-images.githubusercontent.com/3046552/37991128-94856a0e-31c5-11e8-83ed-9197efd93089.png)
> 
> Here's what `InfoButton` looks like when the button color (`baseColor`) is set to the standard PhET yellow. Note that the button color shows through the hole (which is the 'i') in the fontawesome icon.
> 
> ![screenshot_527](https://user-images.githubusercontent.com/3046552/37991196-cc20e556-31c5-11e8-819a-951c903df217.png)


For the record, the default one is the black one. Which one would you prefer?

**Comment by amanda-phet** [comment] 2022-10-17 21:43
I usually choose the blue color when I use this button. I have used it in math sims on game screens, and will be in another upcoming math sim, and I always choose blue. I wonder which sims use black? Should we make blue the default @arouinfar ?

**Comment by arouinfar** [comment] 2022-10-17 22:14
I think I've only used the blue version in the sims I've designed (pendulum-lab, masses-and-springs, fourier-making-waves), though I've seen other colors used in [Build a Nucleus](https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.1/phet/build-a-nucleus_en_phet.html):
<img width="166" alt="image" src="https://user-images.githubusercontent.com/8419308/196293568-594d25b6-373a-4e11-a3d9-5e9cf4f860f1.png">
<img width="303" alt="image" src="https://user-images.githubusercontent.com/8419308/196293605-3c671504-37e3-4d96-92de-1c4b6da9e7d0.png">

Since the majority of sims seem to use a blue icon, I think it makes sense for it to be the default.

**Comment by samreid** [comment] 2024-12-20 00:22
I switched to the info button, and changed the default. I reviewed cases where the color changed. In most cases, it was for the better. Some cases like build-a-nucleus needed to specify fill: 'black'. Closing.

**Closed as completed by samreid** 2024-12-20 00:22 UTC
