### ISSUE TITLE
Vertical points cause inconsistent best fit lines

### ISSUE THREAD

**Issue by BryceAG** [phetsims/least-squares-regression#60] opened 2016-03-30 18:18 UTC
Test device:
Schrodinger, Curie

Operating System:
Windows 8.1, OSX 10.10.5

Browser:
Chrome, safari

Problem description:
If points are placed vertically, the best fit line will sometimes be horizontal, random sloped line in between the points, or no line. also the correlation coefficient will sometimes be NaN, 0, or blank.

Steps to reproduce:
place two or more points directly vertical to each other.

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/14152504/e5b03bd0-f670-11e5-8c7e-78007952891c.png)
![image](https://cloud.githubusercontent.com/assets/15327201/14152524/fed1c5b6-f670-11e5-84ad-1671f87ab967.png)
![image](https://cloud.githubusercontent.com/assets/15327201/14152566/2bab294c-f671-11e5-9a72-26b35d008cf3.png)

Troubleshooting information (do not edit):
Name: ‪Least-Squares Regression‬:‪Least-Squares Regression‬
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.0-rc.1/least-squares-regression_en.html?stringTest=double
Version: 1.1.0-rc.1 2016-03-11 02:08:11 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
Language: en-US
Window: 1920x973
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"9c243fba","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"least-squares-regression":{"sha":"a4164ebe","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

related to phetsims/tasks#542

**Comment by jessegreenberg** [comment] 2016-03-30 20:39
I am assuming that the second screenshot is the most consistent and desired behavior.

**Comment by jessegreenberg** [comment] 2016-03-30 23:06
For the first image, we are getting r=0 because this because JavaScript Math.abs( null ) = 0.  We are returning null in getPearsonCoefficientCorrelation, so we need to handle `null` in PearsonCorrelationCoefficientNode.update().

**Comment by jessegreenberg** [comment] 2016-03-30 23:12
With commit above, we should never hit NaN or 0.00 for RValue when the coefficient is null.

Now trying to repdroduce cases where the line is visible and has some slope when the data points are exactly vertical.

**Comment by jessegreenberg** [comment] 2016-03-30 23:32
In Graph.js we are checking if the xVariance is 0 for if the data points are aligned vertically. But the first image provided can occur if the xVariance is -2.7e-17, which .  Instead of 0 we should be checking for a precision threshold.

**Comment by jessegreenberg** [comment] 2016-03-30 23:45
With the above commit I am unable to reproduce the first or third cases. The second image is the only behavior when data points are stacked.  Leaving open until verified as fixed with testing in the next RC.

**Comment by phet-steele** [comment] 2016-04-08 17:52
Works for me.

**Closed as completed by phet-steele** 2016-04-08 17:52 UTC
Labels: type:bug
